# Generated by Django 3.1.1 on 2020-09-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='demo',
            new_name='folder',
        ),
    ]
